import { DialogControl, DialogDocument, OptionValue, RuntimeId, generatedFunctionName } from './model.js';

export interface GeneratedDialog {
  files: GeneratedFile[];
}

export interface GeneratedFile {
  fileName: string;
  content: string;
}

function generatedFile(fileName: string, content: string): GeneratedDialog {
  return { files: [{ fileName, content }] };
}

function quotePowerShell(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function powerShellValue(value: OptionValue): string {
  if (typeof value === 'string') return quotePowerShell(value);
  if (typeof value === 'boolean') return value ? '$true' : '$false';
  return String(value);
}

function powerShellOptions(control: DialogControl): string {
  const entries = Object.entries(control.options ?? {});
  return entries.length === 0
    ? '@{}'
    : `@{${entries.map(([key, value]) => `${key}=${powerShellValue(value)}`).join('; ')}}`;
}

function generatePowerShell(dialog: DialogDocument): GeneratedDialog {
  const functionName = generatedFunctionName(dialog.id);
  const lines = [
    '# Generated by Salamatrix Studio. Changes will be overwritten.',
    `function ${functionName} {`,
    `    $dialog = $Salamander.ui.Dialog(${quotePowerShell(dialog.title)}, ${dialog.width}, ${dialog.height})`,
    '',
  ];
  for (const control of dialog.controls) {
    const b = control.bounds;
    lines.push(
      `    $dialog.AddControl(${quotePowerShell(control.kind)}, ${quotePowerShell(control.id)}, ${quotePowerShell(control.text)}, ` +
      `$false, $false, 0, @{x=${b.x}; y=${b.y}; width=${b.width}; height=${b.height}}, $false, $false, ${powerShellOptions(control)})`,
    );
    for (const column of control.columns ?? []) {
      lines.push(`    $dialog.AddColumn(${quotePowerShell(control.id)}, ${quotePowerShell(column.title)}, ${column.width})`);
    }
    for (const item of control.items ?? []) {
      lines.push(`    [void]$dialog.AddItem(${quotePowerShell(control.id)}, ${quotePowerShell(item)})`);
    }
    if (control.selectedIndex !== undefined) {
      lines.push(`    [void]$dialog.SetSelectedIndex(${quotePowerShell(control.id)}, ${control.selectedIndex})`);
    }
    if (control.validation) {
      lines.push(`    $dialog.SetValidation(${quotePowerShell(control.id)}, ${control.validation.required ? '$true' : '$false'}, ${quotePowerShell(control.validation.message ?? '')})`);
    }
  }
  lines.push('', '    try {', '        return $dialog.Show()', '    } finally {', '        $dialog.Close()', '    }', '}', '');
  return generatedFile(`${dialog.id}-dialog.generated.ps1`, lines.join('\n'));
}

function js(value: unknown): string {
  return JSON.stringify(value);
}

function generateNode(dialog: DialogDocument): GeneratedDialog {
  const functionName = generatedFunctionName(dialog.id).replace(/^Show/, 'show');
  const lines = [
    '// Generated by Salamatrix Studio. Changes will be overwritten.',
    `export async function ${functionName}(Salamander) {`,
    `  const dialog = await Salamander.ui.dialog(${js(dialog.title)}, { width: ${dialog.width}, height: ${dialog.height} }).create();`,
  ];
  for (const control of dialog.controls) {
    lines.push(`  await dialog.addControl(${js(control.kind)}, ${js(control.id)}, ${js(control.text)}, ${js(control.bounds)}, ${js(control.options ?? {})});`);
    for (const column of control.columns ?? []) lines.push(`  await dialog.addColumn(${js(control.id)}, ${js(column.title)}, ${column.width});`);
    for (const item of control.items ?? []) lines.push(`  await dialog.addItem(${js(control.id)}, ${js(item)});`);
    if (control.selectedIndex !== undefined) lines.push(`  await dialog.setSelectedIndex(${js(control.id)}, ${control.selectedIndex});`);
    if (control.validation) lines.push(`  await dialog.setValidation(${js(control.id)}, ${Boolean(control.validation.required)}, ${js(control.validation.message ?? '')});`);
  }
  lines.push('  try {', '    return await dialog.show();', '  } finally {', '    await dialog.close();', '  }', '}', '');
  return generatedFile(`${dialog.id}-dialog.generated.mjs`, lines.join('\n'));
}

function py(value: unknown): string {
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (value === null) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(py).join(', ')}]`;
  if (typeof value === 'object') return `{${Object.entries(value as object).map(([k, v]) => `${py(k)}: ${py(v)}`).join(', ')}}`;
  return String(value);
}

function generatePython(dialog: DialogDocument): GeneratedDialog {
  const functionName = `show_${dialog.id.replaceAll('-', '_')}_dialog`;
  const lines = [
    '# Generated by Salamatrix Studio. Changes will be overwritten.',
    `def ${functionName}(Salamander):`,
    `    dialog = Salamander.ui.dialog(${py(dialog.title)}, ${dialog.width}, ${dialog.height})`,
  ];
  for (const control of dialog.controls) {
    lines.push(`    dialog.add_control(${py(control.kind)}, ${py(control.id)}, ${py(control.text)}, layout=${py(control.bounds)}, options=${py(control.options ?? {})})`);
    for (const column of control.columns ?? []) lines.push(`    dialog.add_column(${py(control.id)}, ${py(column.title)}, ${column.width})`);
    for (const item of control.items ?? []) lines.push(`    dialog.add_item(${py(control.id)}, ${py(item)})`);
    if (control.selectedIndex !== undefined) lines.push(`    dialog.set_selected_index(${py(control.id)}, ${control.selectedIndex})`);
    if (control.validation) lines.push(`    dialog.set_validation(${py(control.id)}, ${py(Boolean(control.validation.required))}, ${py(control.validation.message ?? '')})`);
  }
  lines.push('    try:', '        return dialog.show()', '    finally:', '        dialog.close()', '');
  return generatedFile(`${dialog.id}_dialog_generated.py`, lines.join('\n'));
}

function php(value: unknown): string {
  if (value === true) return 'true';
  if (value === false) return 'false';
  if (value === null) return 'null';
  if (typeof value === 'string') return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
  if (Array.isArray(value)) return `array(${value.map(php).join(', ')})`;
  if (typeof value === 'object') {
    return `array(${Object.entries(value as object).map(([key, item]) => `${php(key)} => ${php(item)}`).join(', ')})`;
  }
  return String(value);
}

function generatePhp(dialog: DialogDocument): GeneratedDialog {
  const functionName = `show_${dialog.id.replaceAll('-', '_')}_dialog`;
  const lines = [
    '<?php',
    '// Generated by Salamatrix Studio. Changes will be overwritten.',
    `function ${functionName}($Salamander) {`,
    `    $dialog = $Salamander->ui->dialog(${php(dialog.title)}, ${dialog.width}, ${dialog.height});`,
  ];
  for (const control of dialog.controls) {
    const options = control.options ?? {};
    const readOnly = Boolean(options.readOnly);
    const checked = Boolean(options.checked);
    const dialogResult = typeof options.dialogResult === 'number' ? options.dialogResult : 0;
    const keepOpen = Boolean(options.keepOpen);
    const multiline = Boolean(options.multiline);
    lines.push(`    $dialog->addControl(${php(control.kind)}, ${php(control.id)}, ${php(control.text)}, ${php(readOnly)}, ${php(checked)}, ${dialogResult}, ${php(control.bounds)}, ${php(keepOpen)}, ${php(multiline)}, ${php(options)});`);
    for (const column of control.columns ?? []) lines.push(`    $dialog->addColumn(${php(control.id)}, ${php(column.title)}, ${column.width});`);
    for (const item of control.items ?? []) lines.push(`    $dialog->addItem(${php(control.id)}, ${php(item)});`);
    if (control.selectedIndex !== undefined) lines.push(`    $dialog->setSelectedIndex(${php(control.id)}, ${control.selectedIndex});`);
    if (control.validation) lines.push(`    $dialog->setValidation(${php(control.id)}, ${php(Boolean(control.validation.required))}, ${php(control.validation.message ?? '')});`);
  }
  lines.push('    try {', '        return $dialog->show();', '    } finally {', '        $dialog->close();', '    }', '}', '');
  return generatedFile(`${dialog.id}_dialog_generated.php`, lines.join('\n'));
}

const luaOptionNames: Record<string, string> = {
  readOnly: 'read_only', dialogResult: 'dialog_result', keepOpen: 'keep_open',
  styleFlags: 'style_flags', pathSeparator: 'path_separator', toolTip: 'tool_tip',
  actionOpen: 'action_open', actionCommand: 'action_command', actionHint: 'action_hint',
  progressCurrent: 'progress_current', progressTotal: 'progress_total', progressText: 'progress_text',
  indeterminateDuration: 'indeterminate_duration', indeterminateInterval: 'indeterminate_interval',
  textColor: 'text_color', backgroundColor: 'background_color', alignControlId: 'align_control_id',
  buttonMask: 'button_mask',
};

function lua(value: unknown): string {
  if (value === true) return 'true';
  if (value === false) return 'false';
  if (value === null || value === undefined) return 'nil';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `{${value.map(lua).join(', ')}}`;
  if (typeof value === 'object') {
    return `{${Object.entries(value as object).map(([key, item]) => `${luaOptionNames[key] ?? key} = ${lua(item)}`).join(', ')}}`;
  }
  return String(value);
}

function generateLua(dialog: DialogDocument): GeneratedDialog {
  const functionName = `show_${dialog.id.replaceAll('-', '_')}_dialog`;
  const lines = [
    '-- Generated by Salamatrix Studio. Changes will be overwritten.',
    `function ${functionName}(Salamander)`,
    `    local dialog = Salamander.ui.dialog(${lua(dialog.title)}, ${dialog.width}, ${dialog.height})`,
  ];
  for (const control of dialog.controls) {
    const options = { ...control.bounds, ...(control.options ?? {}) };
    lines.push(`    dialog.add_control(${lua(control.kind)}, ${lua(control.id)}, ${lua(control.text)}, ${lua(options)})`);
    for (const column of control.columns ?? []) lines.push(`    dialog.add_column(${lua(control.id)}, ${lua(column.title)}, ${column.width})`);
    for (const item of control.items ?? []) lines.push(`    dialog.add_item(${lua(control.id)}, ${lua(item)})`);
    if (control.selectedIndex !== undefined) lines.push(`    dialog.set_selected_index(${lua(control.id)}, ${control.selectedIndex})`);
    if (control.validation) lines.push(`    dialog.set_validation(${lua(control.id)}, ${lua(Boolean(control.validation.required))}, ${lua(control.validation.message ?? '')})`);
  }
  lines.push('    local shown, result = pcall(dialog.show)', '    dialog.close()', '    if not shown then error(result) end', '    return result', 'end', '');
  return generatedFile(`${dialog.id}_dialog_generated.lua`, lines.join('\n'));
}

const automationKinds = new Set([
  'label', 'groupbox', 'statictext', 'hyperlink', 'progressbar', 'button',
  'arrowbutton', 'textarrowbutton', 'colorarrowbutton', 'listview', 'toolbarheader',
]);

function generateAutomation(dialog: DialogDocument): GeneratedDialog {
  const unsupported = [...new Set(dialog.controls.filter((control) => !automationKinds.has(control.kind)).map((control) => control.kind))];
  if (unsupported.length > 0) {
    throw new Error(`Automation.JScript does not expose these Salamatrix.UI controls: ${unsupported.join(', ')}.`);
  }
  const functionName = generatedFunctionName(dialog.id).replace(/^Show/, 'show');
  const lines = [
    '// Generated by Salamatrix Studio. Changes will be overwritten.',
    `function ${functionName}(Salamander) {`,
    `    var dialog = Salamander.UI.dialog(${js(dialog.title)}, ${dialog.width}, ${dialog.height});`,
  ];
  for (const control of dialog.controls) {
    const options = control.options ?? {};
    const b = control.bounds;
    const styleFlags = typeof options.styleFlags === 'number' ? options.styleFlags : 0;
    const dialogResult = typeof options.dialogResult === 'number' ? options.dialogResult : 0;
    lines.push(`    dialog.add(${js(control.kind)}, ${js(control.id)}, ${js(control.text)}, ${b.x}, ${b.y}, ${b.width}, ${b.height}, ${styleFlags}, ${dialogResult});`);
    const setters: Array<[string, OptionValue, OptionValue?]> = [];
    if (options.progress !== undefined) setters.push(['progress', options.progress]);
    if (options.indeterminateDuration !== undefined) setters.push(['indeterminate', options.indeterminateDuration, options.indeterminateInterval ?? 0]);
    if (options.textColor !== undefined) setters.push(['color', options.textColor, options.backgroundColor ?? 0]);
    for (const name of ['pathSeparator', 'toolTip', 'actionOpen', 'actionCommand', 'actionHint'] as const) {
      if (options[name] !== undefined) setters.push([name, options[name]]);
    }
    if (options.alignControlId !== undefined) setters.push(['toolbarHeader', options.alignControlId, options.buttonMask ?? 0]);
    for (const [name, first, second] of setters) {
      lines.push(`    dialog.set(${js(control.id)}, ${js(name)}, ${js(first)}${second === undefined ? '' : `, ${js(second)}`});`);
    }
  }
  lines.push('    try {', '        return dialog.show();', '    } finally {', '        dialog.close();', '    }', '}', '');
  return generatedFile(`${dialog.id}-dialog.generated.js`, lines.join('\n'));
}

const cppControlKinds: Record<DialogControl['kind'], string> = {
  label: 'ControlKindLabel', statictext: 'ControlKindStaticText', textbox: 'ControlKindTextBox',
  checkbox: 'ControlKindCheckBox', radio: 'ControlKindRadioButton', combobox: 'ControlKindComboBox',
  button: 'ControlKindButton', listview: 'ControlKindListView', treeview: 'ControlKindTreeView',
  tabcontrol: 'ControlKindTabControl', folderpicker: 'ControlKindFolderPicker', filepicker: 'ControlKindFilePicker',
  groupbox: 'ControlKindGroupBox', hyperlink: 'ControlKindHyperLink', progressbar: 'ControlKindProgressBar',
  arrowbutton: 'ControlKindArrowButton', textarrowbutton: 'ControlKindTextArrowButton',
  colorarrowbutton: 'ControlKindColorArrowButton', toolbarheader: 'ControlKindToolbarHeader',
};

function cppString(value: string): string {
  return JSON.stringify(value).replaceAll('\\u2028', '\\u2028').replaceAll('\\u2029', '\\u2029');
}

function cppMethodName(id: string): string {
  return generatedFunctionName(id);
}

function generateCpp(dialog: DialogDocument): GeneratedDialog {
  const method = cppMethodName(dialog.id);
  const headerName = `${dialog.id}-dialog.generated.h`;
  const header = [
    '// Generated by Salamatrix Studio. Changes will be overwritten.',
    '#pragma once',
    '#include <windows.h>',
    'class CSalamanderGeneralAbstract;',
    '',
    `int ${method}(CSalamanderGeneralAbstract* SalamanderGeneral, HWND parent);`,
    '',
  ].join('\n');
  const lines = [
    '// Generated by Salamatrix Studio. Changes will be overwritten.',
    `#include ${cppString(headerName)}`,
    '#include "spl_gen.h"',
    '#include "salamatrix_runtime.h"',
    '',
    `int ${method}(CSalamanderGeneralAbstract* SalamanderGeneral, HWND parent)`,
    '{',
    '    CSalamanderServiceQuery query;',
    '    CSalamanderServiceResult service;',
    '    query.ServiceId = SALAMATRIX_SERVICE_UI;',
    '    query.MinimumVersion = SALAMATRIX_UI_VERSION_1_4;',
    '    query.Flags = 0;',
    '    if (SalamanderGeneral == NULL || !SalamanderGeneral->QueryService(&query, &service)) return 0;',
    '    Salamatrix::UI::IUIService* ui = static_cast<Salamatrix::UI::IUIService*>(service.Interface);',
    '    Salamatrix::UI::DialogOptions dialogOptions;',
    `    dialogOptions.Title = ${cppString(dialog.title)};`,
    '    dialogOptions.Parent = parent;',
    `    dialogOptions.Width = ${dialog.width};`,
    `    dialogOptions.Height = ${dialog.height};`,
    '    Salamatrix::UI::IDialog* dialog = ui->CreateSalamatrixDialog(dialogOptions);',
    '    if (dialog == NULL) return 0;',
    '',
  ];
  dialog.controls.forEach((control, index) => {
    const b = control.bounds;
    const options = control.options ?? {};
    lines.push('    {', '        Salamatrix::UI::ControlOptions options;', `        options.Id = ${cppString(control.id)};`, `        options.Text = ${cppString(control.text)};`);
    if (options.readOnly !== undefined) lines.push(`        options.ReadOnly = ${options.readOnly ? 'TRUE' : 'FALSE'};`);
    if (options.checked !== undefined) lines.push(`        options.Checked = ${options.checked ? 'TRUE' : 'FALSE'};`);
    if (options.dialogResult !== undefined) lines.push(`        options.DialogResult = ${Number(options.dialogResult)};`);
    if (options.keepOpen !== undefined) lines.push(`        options.KeepOpen = ${options.keepOpen ? 'TRUE' : 'FALSE'};`);
    if (options.multiline !== undefined) lines.push(`        options.Multiline = ${options.multiline ? 'TRUE' : 'FALSE'};`);
    if (typeof options.filter === 'string') lines.push(`        options.FileFilter = ${cppString(options.filter)};`);
    if (options.save !== undefined) lines.push(`        options.FileSave = ${options.save ? 'TRUE' : 'FALSE'};`);
    lines.push('        Salamatrix::UI::ControlLayout layout;', '        layout.HasBounds = TRUE;', `        layout.X = ${b.x}; layout.Y = ${b.y};`, `        layout.Width = ${b.width}; layout.Height = ${b.height};`, `        Salamatrix::UI::IControl* control${index} = dialog->AddControlEx(Salamatrix::UI::${cppControlKinds[control.kind]}, options, layout);`, `        if (control${index} == NULL) { ui->DestroyDialog(dialog); return 0; }`);
    if (options.styleFlags !== undefined) lines.push(`        control${index}->SetStyleFlags(${Number(options.styleFlags)});`);
    if (typeof options.pathSeparator === 'string' && options.pathSeparator.length > 0) lines.push(`        control${index}->SetPathSeparator(${cppString(options.pathSeparator)}[0]);`);
    if (typeof options.toolTip === 'string') lines.push(`        control${index}->SetToolTipText(${cppString(options.toolTip)});`);
    if (typeof options.actionOpen === 'string') lines.push(`        control${index}->SetActionOpen(${cppString(options.actionOpen)});`);
    if (options.actionCommand !== undefined) lines.push(`        control${index}->SetActionPostCommand(static_cast<WORD>(${Number(options.actionCommand)}));`);
    if (typeof options.actionHint === 'string') lines.push(`        control${index}->SetActionShowHint(${cppString(options.actionHint)});`);
    if (options.progress !== undefined) lines.push(`        control${index}->SetProgress(${Number(options.progress)}${typeof options.progressText === 'string' ? `, ${cppString(options.progressText)}` : ''});`);
    if (options.progressCurrent !== undefined || options.progressTotal !== undefined) lines.push(`        control${index}->SetProgressValues(${Number(options.progressCurrent ?? 0)}, ${Number(options.progressTotal ?? 0)}${typeof options.progressText === 'string' ? `, ${cppString(options.progressText)}` : ''});`);
    if (options.indeterminateDuration !== undefined) lines.push(`        control${index}->SetIndeterminateTiming(${Number(options.indeterminateDuration)}, ${Number(options.indeterminateInterval ?? 50)});`);
    if (options.textColor !== undefined || options.backgroundColor !== undefined) lines.push(`        control${index}->SetColor(${Number(options.textColor ?? 0)}, ${Number(options.backgroundColor ?? 0xFFFFFF)});`);
    if (typeof options.alignControlId === 'string') lines.push(`        control${index}->SetToolbarHeader(${cppString(options.alignControlId)}, ${Number(options.buttonMask ?? 0)});`);
    for (const column of control.columns ?? []) lines.push(`        control${index}->AddColumn(${cppString(column.title)}, ${column.width});`);
    for (const item of control.items ?? []) lines.push(`        control${index}->AddItem(${cppString(item)});`);
    if (control.selectedIndex !== undefined) lines.push(`        control${index}->SetSelectedIndex(${control.selectedIndex});`);
    if (control.validation?.required !== undefined) lines.push(`        control${index}->SetRequired(${control.validation.required ? 'TRUE' : 'FALSE'});`);
    if (control.validation?.message !== undefined) lines.push(`        control${index}->SetValidationMessage(${cppString(control.validation.message)});`);
    lines.push('    }');
  });
  lines.push('', '    const int result = dialog->ShowModal();', '    ui->DestroyDialog(dialog);', '    return result;', '}', '');
  return {
    files: [
      { fileName: headerName, content: header },
      { fileName: `${dialog.id}-dialog.generated.cpp`, content: lines.join('\n') },
    ],
  };
}

export function generateDialog(dialog: DialogDocument, runtime: RuntimeId): GeneratedDialog {
  switch (runtime) {
    case 'PowerShell': return generatePowerShell(dialog);
    case 'Python.CPython': return generatePython(dialog);
    case 'JavaScript.Node': return generateNode(dialog);
    case 'PHP.CLI': return generatePhp(dialog);
    case 'Lua': return generateLua(dialog);
    case 'Automation.JScript': return generateAutomation(dialog);
    case 'Native.Cpp': return generateCpp(dialog);
    default:
      throw new Error(`Unsupported Salamatrix Studio runtime: ${runtime}.`);
  }
}

export function runtimeFromManifest(manifest: unknown): RuntimeId {
  const value = manifest as { runtime?: string | { id?: string } };
  const runtime = typeof value.runtime === 'string' ? value.runtime : value.runtime?.id;
  if (!runtime) throw new Error('extension.json does not declare a runtime.');
  return runtime as RuntimeId;
}
