import { DialogControl, DialogDocument, OptionValue, RuntimeId, generatedFunctionName } from './model.js';

export interface GeneratedDialog {
  fileName: string;
  content: string;
}

function quotePowerShell(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function powerShellValue(value: OptionValue): string {
  if (typeof value === 'string') return quotePowerShell(value);
  if (typeof value === 'boolean') return value ? '$true' : '$false';
  return String(value);
}

function powerShellOptions(control: DialogControl): string {
  const entries = Object.entries(control.options ?? {});
  return entries.length === 0
    ? '@{}'
    : `@{${entries.map(([key, value]) => `${key}=${powerShellValue(value)}`).join('; ')}}`;
}

function generatePowerShell(dialog: DialogDocument): GeneratedDialog {
  const functionName = generatedFunctionName(dialog.id);
  const lines = [
    '# Generated by Salamatrix Studio. Changes will be overwritten.',
    `function ${functionName} {`,
    `    $dialog = $Salamander.ui.Dialog(${quotePowerShell(dialog.title)}, ${dialog.width}, ${dialog.height})`,
    '',
  ];
  for (const control of dialog.controls) {
    const b = control.bounds;
    lines.push(
      `    $dialog.AddControl(${quotePowerShell(control.kind)}, ${quotePowerShell(control.id)}, ${quotePowerShell(control.text)}, ` +
      `$false, $false, 0, @{x=${b.x}; y=${b.y}; width=${b.width}; height=${b.height}}, $false, $false, ${powerShellOptions(control)})`,
    );
    for (const column of control.columns ?? []) {
      lines.push(`    $dialog.AddColumn(${quotePowerShell(control.id)}, ${quotePowerShell(column.title)}, ${column.width})`);
    }
    for (const item of control.items ?? []) {
      lines.push(`    [void]$dialog.AddItem(${quotePowerShell(control.id)}, ${quotePowerShell(item)})`);
    }
    if (control.selectedIndex !== undefined) {
      lines.push(`    [void]$dialog.SetSelectedIndex(${quotePowerShell(control.id)}, ${control.selectedIndex})`);
    }
    if (control.validation) {
      lines.push(`    $dialog.SetValidation(${quotePowerShell(control.id)}, ${control.validation.required ? '$true' : '$false'}, ${quotePowerShell(control.validation.message ?? '')})`);
    }
  }
  lines.push('', '    try {', '        return $dialog.Show()', '    } finally {', '        $dialog.Close()', '    }', '}', '');
  return { fileName: `${dialog.id}-dialog.generated.ps1`, content: lines.join('\n') };
}

function js(value: unknown): string {
  return JSON.stringify(value);
}

function generateNode(dialog: DialogDocument): GeneratedDialog {
  const functionName = generatedFunctionName(dialog.id).replace(/^Show/, 'show');
  const lines = [
    '// Generated by Salamatrix Studio. Changes will be overwritten.',
    `export async function ${functionName}(Salamander) {`,
    `  const dialog = await Salamander.ui.dialog(${js(dialog.title)}, { width: ${dialog.width}, height: ${dialog.height} }).create();`,
  ];
  for (const control of dialog.controls) {
    lines.push(`  await dialog.addControl(${js(control.kind)}, ${js(control.id)}, ${js(control.text)}, ${js(control.bounds)}, ${js(control.options ?? {})});`);
    for (const column of control.columns ?? []) lines.push(`  await dialog.addColumn(${js(control.id)}, ${js(column.title)}, ${column.width});`);
    for (const item of control.items ?? []) lines.push(`  await dialog.addItem(${js(control.id)}, ${js(item)});`);
    if (control.selectedIndex !== undefined) lines.push(`  await dialog.setSelectedIndex(${js(control.id)}, ${control.selectedIndex});`);
    if (control.validation) lines.push(`  await dialog.setValidation(${js(control.id)}, ${Boolean(control.validation.required)}, ${js(control.validation.message ?? '')});`);
  }
  lines.push('  try {', '    return await dialog.show();', '  } finally {', '    await dialog.close();', '  }', '}', '');
  return { fileName: `${dialog.id}-dialog.generated.mjs`, content: lines.join('\n') };
}

function py(value: unknown): string {
  if (value === true) return 'True';
  if (value === false) return 'False';
  if (value === null) return 'None';
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(py).join(', ')}]`;
  if (typeof value === 'object') return `{${Object.entries(value as object).map(([k, v]) => `${py(k)}: ${py(v)}`).join(', ')}}`;
  return String(value);
}

function generatePython(dialog: DialogDocument): GeneratedDialog {
  const functionName = `show_${dialog.id.replaceAll('-', '_')}_dialog`;
  const lines = [
    '# Generated by Salamatrix Studio. Changes will be overwritten.',
    `def ${functionName}(Salamander):`,
    `    dialog = Salamander.ui.dialog(${py(dialog.title)}, ${dialog.width}, ${dialog.height})`,
  ];
  for (const control of dialog.controls) {
    lines.push(`    dialog.add_control(${py(control.kind)}, ${py(control.id)}, ${py(control.text)}, layout=${py(control.bounds)}, options=${py(control.options ?? {})})`);
    for (const column of control.columns ?? []) lines.push(`    dialog.add_column(${py(control.id)}, ${py(column.title)}, ${column.width})`);
    for (const item of control.items ?? []) lines.push(`    dialog.add_item(${py(control.id)}, ${py(item)})`);
    if (control.selectedIndex !== undefined) lines.push(`    dialog.set_selected_index(${py(control.id)}, ${control.selectedIndex})`);
    if (control.validation) lines.push(`    dialog.set_validation(${py(control.id)}, ${py(Boolean(control.validation.required))}, ${py(control.validation.message ?? '')})`);
  }
  lines.push('    try:', '        return dialog.show()', '    finally:', '        dialog.close()', '');
  return { fileName: `${dialog.id}_dialog_generated.py`, content: lines.join('\n') };
}

export function generateDialog(dialog: DialogDocument, runtime: RuntimeId): GeneratedDialog {
  switch (runtime) {
    case 'PowerShell': return generatePowerShell(dialog);
    case 'Python.CPython': return generatePython(dialog);
    case 'JavaScript.Node': return generateNode(dialog);
    default:
      throw new Error(`The ${runtime} generator is planned but not implemented in this first Studio slice.`);
  }
}

export function runtimeFromManifest(manifest: unknown): RuntimeId {
  const value = manifest as { runtime?: string | { id?: string } };
  const runtime = typeof value.runtime === 'string' ? value.runtime : value.runtime?.id;
  if (!runtime) throw new Error('extension.json does not declare a runtime.');
  return runtime as RuntimeId;
}
